object Versions {
    const val kotlinxSerialization = "1.3.0"
    const val serializationConverter = "0.8.0"
    const val navigation = "2.4.0"
    const val room = "2.4.2"
    const val koin = "3.2.0"
    const val interceptor = "4.10.0"
    const val moshi = "1.13.0"
    const val moshiConvertor = "2.9.0"
    const val retrofit = "2.9.0"
    const val appCompat = "1.4.0"
    const val gradle = "7.2.1"
    const val kotlin = "1.7.0"
    const val coroutines = "1.3.9"
    const val lifecycle = "2.3.1"
    const val material = "1.4.0"
    const val constraintLayout = "2.1.1"
    const val coroutinesCore = "1.4.1"
    const val dbCipher = "4.4.0"
    const val sqlite = "2.2.0"
    const val splash = "1.0.0-rc01"
    const val dataBinding = "7.2.1"
    const val coil = "2.1.0"
}